/** Russian — keys must match `telegram-dict-uz.ts` exactly. */
export const TELEGRAM_DICT_RU: Record<string, string> = {
  'currency.som': 'сум',
  'common.guest': 'Гость',
  'common.dash': '—',
  'common.moreItems': '... и ещё {{count}}',

  'orderStatus.PENDING': 'Ожидает',
  'orderStatus.CONFIRMED': 'Заказ принят',
  'orderStatus.PROCESSING': 'Готовится',
  'orderStatus.SHIPPED': 'Отправлен',
  'orderStatus.DELIVERED': 'Доставлен',
  'orderStatus.CANCELLED': 'Отменён',
  'orderStatus.PICKUP_SHIPPED': 'Готов к самовывозу',
  'orderStatus.PICKUP_DELIVERED': 'Выдан (самовывоз)',

  'paymentStatus.PENDING': 'Ожидает',
  'paymentStatus.PAID': 'Оплачен',
  'paymentStatus.FAILED': 'Неуспешно',
  'paymentStatus.REFUNDED': 'Возвращён',

  'paymentMethod.CLICK': 'Click',
  'paymentMethod.PAYME': 'Payme',
  'paymentMethod.CASH': 'Наличные',
  'paymentMethod.CARD_ON_DELIVERY': 'Карта при получении',

  'deliveryType.DELIVERY': 'Доставка',
  'deliveryType.PICKUP': 'Самовывоз',

  'kb.confirm': '✓ Подтвердить',
  'kb.cancelOrder': '✕ Отменить',
  'kb.processing': 'В обработку',
  'kb.shipped': 'Отправлен',
  'kb.delivered': '✓ Доставлен',
  'kb.detail': '📄 Подробнее',
  'kb.orders': '📋 Заказы',
  'kb.markPaid': '💳 Оплата получена',
  'kb.myOrders': '📋 Мои заказы',

  'menu.backMain': '◀️ Главное меню',
  'menu.orders': '📋 Заказы',
  'menu.stats': '📊 Статистика',
  'menu.today': '📅 Сегодня',
  'menu.pending': '⏳ Ожидают',
  'menu.help': '❓ Помощь',
  'menu.shopWeb': '🛒 Магазин (веб)',
  'menu.shopWebShort': 'Магазин (веб)',
  'menu.adminPanel': '🌐 Админ-панель',
  'menu.sellerPanel': '🌐 Кабинет продавца',
  'menu.buyerCatalog': '🛒 Магазин (каталог, корзина)',
  'menu.buyerMyOrders': '📋 Мои заказы',
  'menu.modProducts': '📦 Модерация (товары)',
  'menu.modReviews': '💬 Отзывы',

  'cmd.start': 'Запуск бота',
  'cmd.code': 'Код привязки (админ / продавец)',
  'cmd.shop': 'Открыть магазин (веб)',
  'cmd.orders': 'Мои заказы / продавец: заказы',
  'cmd.help': 'Помощь',
  'cmd.lang': 'Выбор языка',

  'lang.prompt': '🌐 <b>Язык бота</b>\n\nТекущий: <b>{{current}}</b>\n\nВыберите кнопкой:',
  'lang.nameUz': 'Oʻzbekcha',
  'lang.nameRu': 'Русский',
  'lang.saved': 'Язык: {{lang}}',

  'menuIntro.title': '<b>Бот Oline Bozor</b>',
  'menuIntro.body': 'Используйте кнопки ниже. В уведомлении о заказе «Подробнее» — полная информация.',

  'link.expired': '⏱ Ссылка истекла. Нажмите «Привязать Telegram» на сайте ещё раз.',
  'link.loginOnly': 'Эта ссылка для входа. Используйте кнопку «Войти через Telegram» на сайте.',
  'link.accountLinked':
    '✅ Telegram привязан к аккаунту. Вернитесь в окно сайта — уведомления о заказах будут приходить сюда.',
  'link.loginExpired': '⏱ Ссылка истекла. Нажмите «Войти через Telegram» на сайте ещё раз.',
  'link.loginError': 'Произошла ошибка. Попробуйте снова.',
  'link.loginOk': '✅ Вы вошли в систему. Вернитесь в окно сайта — вход выполнится автоматически.',

  'code.reply':
    '🔑 <b>Код привязки:</b> <code>{{code}}</code>\n\nВведите его на сайте в <b>Настройки → Telegram</b>. Действует 15 минут.',
  'code.error': 'Не удалось создать код. Позже отправьте /code.',

  'welcome.admin':
    'Здравствуйте! <b>Oline Bozor</b> — <b>Админ</b>.\n\nКнопки: заказы, статистика, модерация, веб-панель. Код привязки — <b>/code</b>.',
  'welcome.seller':
    'Здравствуйте! <b>Oline Bozor</b> — <b>Продавец</b>.\n\nКнопки: заказы, статистика, веб-панель. Код привязки — <b>/code</b>.',
  'welcome.buyerNamed': 'Привет, {{name}}! <b>Oline Bozor</b> — покупатель.\n\nКаталог, корзина и заказы — кнопкой ниже.',
  'welcome.buyerAnon':
    'Здравствуйте! Магазин <b>Oline Bozor</b>.\n\nОткройте каталог кнопкой ниже. При первом открытии регистрация выполнится автоматически.',
  'welcome.useButtons': 'Используйте кнопки или команды ниже:',
  'shop.hint': '🛒 Магазин — каталог, корзина и заказы. Нажмите кнопку ниже:',
  'unknown.useMenu': 'Используйте кнопки или команды ниже:',

  'orders.admin.empty': '📋 <b>Админ: заказы</b>\n\nПока заказов нет.',
  'orders.admin.list': '📋 <b>Админ: последние заказы</b>\n\nПодробности — по кнопкам:\n\n',
  'orders.seller.unlink': 'Сначала привяжите магазин: Настройки → Telegram и введите код.',
  'orders.seller.empty': 'Активных заказов нет.',
  'orders.seller.list': '<b>Активные заказы</b>\n\nНажмите кнопку для подробностей:\n\n',
  'orders.line': '• {{number}} — {{status}} — {{amount}} {{currency}}',
  'orders.lineEmoji': '📋 {{number}} — {{status}} — {{amount}} {{currency}}',

  'stats.unlinkShop': 'Сначала привяжите магазин: Настройки → Telegram и введите код.',
  'stats.unlinkAccount': 'Сначала привяжите аккаунт: введите код в настройках.',
  'stats.admin.title': '📊 <b>Статистика платформы</b>',
  'stats.admin.users': '👥 Пользователи',
  'stats.admin.products': '📦 Товары',
  'stats.admin.orders': '📋 Заказы',
  'stats.admin.revenue': '💰 Выручка (оплачено)',
  'stats.admin.moderation': '⏳ Ожидает модерации',
  'stats.admin.modProducts': '  • Товары',
  'stats.admin.modReviews': '  • Отзывы',
  'stats.seller.title': '📊 <b>Статистика вашего магазина</b>',
  'stats.seller.totalOrders': '📋 Всего заказов',
  'stats.seller.pending': '⏳ Ожидают',
  'stats.seller.products': '📦 Товары',
  'stats.seller.revenue': '💰 Выручка (оплачено)',

  'pending.admin.title': '⏳ <b>Ожидает модерации</b>',
  'pending.admin.products': '📦 Товары',
  'pending.admin.reviews': '💬 Отзывы',
  'pending.admin.webHint': '\n\nОткройте в веб-панели по кнопкам.',
  'pending.seller.count': '⏳ Заказов в ожидании: <b>{{count}}</b>',
  'pending.seller.none': '⏳ Заказов в ожидании нет.',

  'today.admin.title': '📅 <b>Сегодня (платформа)</b>',
  'today.seller.title': '📅 <b>Сегодня (ваш магазин)</b>',
  'today.orders': '📋 Заказы',
  'today.paidSum': '💰 Оплачено',

  'buyer.orders.needOpen':
    'Чтобы видеть «Мои заказы», сначала откройте магазин (кнопка ниже) и войдите один раз — затем список появится здесь.',
  'buyer.orders.empty': '📋 <b>Мои заказы</b>\n\nПока заказов нет. Совершите покупку в магазине кнопкой ниже.',
  'buyer.orders.list': '📋 <b>Мои заказы</b>\n\nПодробности — по кнопкам:\n\n',

  'help.seller':
    '<b>Бот Oline Bozor</b>\n\nДля продавцов и админа. Сначала введите код в настройках.\n\n<b>Команды:</b>\n• /code — код привязки (в настройках админа или продавца)\n• /start, /link — меню / код\n• /orders — активные заказы\n• /stats — статистика\n• /pending — ожидающие\n• /today — заказы за сегодня\n• /lang — язык (узбекский / русский)\n• /help — помощь\n\nВ уведомлении о заказе меняйте статус кнопками.',
  'help.buyer':
    '<b>Oline Bozor — для покупателей</b>\n\n• <b>/start</b> — меню\n• <b>/shop</b> — открыть магазин (веб)\n• <b>/orders</b> — мои заказы\n• <b>/lang</b> — язык (узбекский / русский)\n• <b>/help</b> — помощь\n\nКнопка магазина — каталог, корзина и оформление. При первом открытии регистрация автоматически.',

  'cb.openShopFirst': 'Сначала откройте магазин и войдите.',
  'cb.loading': 'Загрузка…',
  'cb.orderNotFound': 'Заказ не найден.',
  'cb.denied': 'Нет доступа.',
  'cb.shopNotLinked': 'Магазин не привязан.',
  'cb.prepaidBlock': 'До оплаты Click/Payme нельзя отметить отправку/доставку.',
  'cb.cashOnlyMark': 'Только для наличных или карты при получении.',
  'cb.alreadyPaid': 'Оплата уже отмечена.',
  'cb.markedPaid': 'Оплата отмечена.',
  'cb.badStatus': 'Такой статус недоступен.',
  'cb.statusPrefix': 'Статус: ',
  'cb.updated': '✅ Обновлено: ',
  'cb.orderFallback': 'Заказ',

  'detail.title': '📄 <b>Заказ: подробно</b>',
  'detail.adminTitle': '📄 <b>АДМИН: заказ подробно</b>',
  'detail.number': '📋 Номер',
  'detail.status': '📌 Статус',
  'detail.payment': '💳 Оплата',
  'detail.delivery': '🚚 Доставка',
  'detail.total': '💰 Итого',
  'detail.date': '📅 Дата',
  'detail.buyer': '👤 Покупатель',
  'detail.contact': '📞 Контакт',
  'detail.seller': '🏪 Продавец',
  'detail.address': '📍 Адрес',
  'detail.notes': '📝 Комментарий',
  'detail.products': '<b>Товары:</b>',
  'detail.itemLine': '  • {{title}}{{variant}} × {{qty}} = {{price}} {{currency}}',

  'seller.notify.new': '🆕 <b>Новый заказ</b>',
  'seller.notify.updated': '📢 <b>Заказ обновлён</b>',
  'seller.notify.buyer': '👤 Покупатель',
  'seller.notify.total': '💰 Итого',
  'seller.notify.date': '📅 Дата',
  'seller.notify.products': '<b>Товары:</b>',
  'seller.notify.item': '  • {{title}} × {{qty}} — {{price}} {{currency}}',

  'buyer.notify.new': '✅ <b>Ваш заказ принят</b>',
  'buyer.notify.updated': '📢 <b>Ваш заказ обновлён</b>',
  'buyer.notify.seller': '🏪 Продавец',
  'buyer.notify.newStatus': '📌 Новый статус',

  'admin.notify.new': '📦 <b>АДМИН: новый заказ</b>',
  'admin.notify.updated': '📢 <b>АДМИН: заказ обновлён</b>',
  'admin.notify.arrow': ' → ',
  'admin.notify.state': '📌 Статус',

  'review.seller.new': '💬 <b>Новый отзыв</b>',
  'review.seller.link': '📋 Отзывы',

  'admin.product.new': '📦 <b>АДМИН: новый товар (ожидает модерации)</b>',
  'admin.product.id': 'ID',
  'admin.product.name': 'Название',
  'admin.product.shop': 'Магазин',
  'admin.product.open': '📦 Модерация',

  'admin.application.new': '📝 <b>Новая заявка: стать продавцом</b>',
  'admin.application.shopName': '🏪 Название магазина',
  'admin.application.user': '👤 Заявитель',
  'admin.application.msg': '\n💬 Сообщение',
  'admin.application.approve': '✅ Одобрить',
  'admin.application.reject': '❌ Отклонить',
  'admin.application.list': '📋 Список заявок',

  'admin.review.new': '💬 <b>АДМИН: новый отзыв (ожидает модерации)</b>',
  'admin.review.open': '💬 Отзывы',

  'seller.app.approvedCb': '✅ Заявка одобрена.',
  'seller.app.rejectedCb': '❌ Заявка отклонена.',
  'seller.app.approvedEdit': '\n\n✅ <b>Одобрено</b>',
  'seller.app.rejectedEdit': '\n\n❌ <b>Отклонено</b>',
  'seller.app.adminMissing': 'Админ не найден.',
  'seller.app.notFound': 'Заявка не найдена.',
  'seller.app.already': 'Заявка уже обработана.',
};
